version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env.prod.db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn ToDoSite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./ToDoSite:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.prod.web
    depends_on:
      db:
        condition: service_healthy
volumes:
  db:
    driver: local
